### ISSUE TITLE
Port Issues

### ISSUE THREAD

**Issue by jonrrivera** [urre/wordpress-nginx-docker-compose#40]
Hi, thanks for the awesome repo. I followed the instructions and at the end, I am getting this port issue after running the `docker-compose up -d` command. 

<img width="783" alt="Screen Shot 2020-05-05 at 10 01 34 PM" src="https://user-images.githubusercontent.com/18686388/81132366-2fadd880-8f1c-11ea-9fc6-21eb126a9ec2.png">

Not sure how to move forward from this. Help please !

**Comment by jonrrivera** [comment]
Fixed by changing the ports under mysql to 3333:3333. not sure if this is a correct implementation. 

<img width="478" alt="Screen Shot 2020-05-05 at 10 33 05 PM" src="https://user-images.githubusercontent.com/18686388/81133709-7998bd80-8f20-11ea-9d66-77c0895b5c77.png">

**Comment by urre** [comment]
@jonrrivera you probably just had some other things running on 3306? mysql often runs on that port default on your system if using outside of Docker

**Comment by RobHowdle** [comment]
I know this is an old issue but I had this same problem. Didn't see this until now. I'm using Ubuntu 20 and doing a netstat command in terminal I found mysql and apache were both running on the correct ports however the problem was that they were not dockers mysql and apache, it was ubuntus. I assumed it was the same thing but apparently not. Running the following commands fixed it:
```
systemctl stop docker
systemctl stop mysql
systemctl stop apache2
```

// This command just checked nothing was then running on those ports
`sudo netstat-tlnp`

`docker-compose up`
