### ISSUE TITLE
Certificates file type, import into Firefox and Chrome

### ISSUE THREAD

**Issue by renestalder** [urre/wordpress-nginx-docker-compose#60]
I have nearly zero knowledge about SSL and certificates, so I'm already sorry if this question might be out of scope of this project.

I could set up nearly everything, except for the certs. The creation works, adding it to the certificate store in Linux works and updating the host file works with the scripts. Yet, Firefox and Chromium both seems to manage their stores and don't take the certificate from the OS (at least on Ubuntu/Pop_OS).

Now both browsers accept importing a `pfx` file, so I generated a pfx file from the given cert file and imported it into both browsers, but apparently that doesn't seem to work.

Do I miss something to make this working flawlessly with Chromium and Firefox?

**Comment by urre** [comment]
@renestalder I haven't got Pop_OS installed so can't test this. Closing this but if you find a solution, please put up a PR.

**Comment by renestalder** [comment]
@urre :+1: 

I hope I'm still allowed to ask: On macOS and Windows (supposedly the two OS you tested), does Firefox automatically pickup the OS certificates or do you have to manually import it in the settings?

**Comment by urre** [comment]
@renestalder sure! No, Firefox doesn't trust the certs using the script. So import it in the settings. (Only Chrome and Safari). Short note about it in the [readme here](https://github.com/urre/wordpress-nginx-docker-compose#trust-the-cert)

Will update the readme also soon with how to run this setup without SSL

**Comment by renestalder** [comment]
@urre And you're able to import the cert generated by your scripts in Firefox? I couldn't. I only could after generating a pfx from the cert file separately. Not that this made the certificate to work, but the import dialog didn't even allow to import the cert file.

**Comment by urre** [comment]
@renestalder you are right! My instructions wasn't up to date for Firefox. 

I decided to switch to mkcert to create the certs instead of the custom script. It handles everything. Creating a locally-trusted development certificate and supporting Windows, Linux and Mac. This also works in Firefox.

Let me know if you have more questions. [Checkout the updated readme file](https://github.com/urre/wordpress-nginx-docker-compose)

Screenshot from Firefox:
![](https://res.cloudinary.com/urre/image/upload/v1607013296/screenshots/ocbtxzih5mvabmblwwwi.png)

**Comment by renestalder** [comment]
@urre Aaahhh, that's so great. That would have been the next thing I would have tried; using mkcert. Thank you so much.
